API_URL="https://content-recommendation-function.azurewebsites.net"

AZURE_CONNECTION_STRING="DefaultEndpointsProtocol=https;AccountName=recoappstorage123;AccountKey=qzh+rJ+fD0K+iiuqDDzJrrBA8dH+V+xQX3SrFvArTecW0x4c711t/xGLvZ2Umi9TclH2c0d2PskO+ASt2RlB4Q==;EndpointSuffix=core.windows.net"
KEY_VAULT_URL="https://reco-key-vault.vault.azure.net/"
SCM_DO_BUILD_DURING_DEPLOYMENT="true"
STORAGE_ACCOUNT_URL="https://recoappstorage123.blob.core.windows.net"
STORAGE_CONNECTION_STRING="DefaultEndpointsProtocol=https;AccountName=recoappstorage123;AccountKey=qzh+rJ+fD0K+iiuqDDzJrrBA8dH+V+xQX3SrFvArTecW0x4c711t/xGLvZ2Umi9TclH2c0d2PskO+ASt2RlB4Q==;EndpointSuffix=core.windows.net"
WEBSITE_HEALTHCHECK_MAXPINGFAILURES="10"
WEBSITES_HEALTH_CHECK_PORT="8080"
APPLICATIONINSIGHTS_CONNECTION_STRING="InstrumentationKey=88c8888d-ef90-4ef8-8c88-435918646fbf;IngestionEndpoint=https://francecentral-1.in.applicationinsights.azure.com/;LiveEndpoint=https://francecentral.livediagnostics.monitor.azure.com/;ApplicationId=adf1e464-c67b-4901-b57b-ac38bf91cf5a"
AzureWebJobsStorage="DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=recoappstorage123;AccountKey=qzh+rJ+fD0K+iiuqDDzJrrBA8dH+V+xQX3SrFvArTecW0x4c711t/xGLvZ2Umi9TclH2c0d2PskO+ASt2RlB4Q=="
FUNCTIONS_EXTENSION_VERSION="~4"
FUNCTIONS_WORKER_RUNTIME="python"
WEBSITE_CONTENTAZUREFILECONNECTIONSTRING="DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=recoappstorage123;AccountKey=qzh+rJ+fD0K+iiuqDDzJrrBA8dH+V+xQX3SrFvArTecW0x4c711t/xGLvZ2Umi9TclH2c0d2PskO+ASt2RlB4Q=="
WEBSITE_CONTENTSHARE="content-recommendation-function03b6e5604a1d"
WEBSITE_ENABLE_SYNC_UPDATE_SITE="true"
WEBSITE_RUN_FROM_PACKAGE="https://recoappstorage123.blob.core.windows.net/github-actions-deploy/Functionapp_202512913213537.zip?sv=2025-05-05&st=2025-12-09T13%3A16%3A03Z&se=2026-12-09T13%3A21%3A03Z&sr=b&sp=r&sig=vtFvhYT%2BjSjr5qqfLYxrH8JxD0FxOi9NSBGK6DgvsxQ%3D"
